// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADISSP7mx0lLpYeeqnfb_bC5iNDmk3SMI',
    appId: '1:54170088721:web:31917346b9fd79926a48b0',
    messagingSenderId: '54170088721',
    projectId: 'ayursage-146ed',
    authDomain: 'ayursage-146ed.firebaseapp.com',
    storageBucket: 'ayursage-146ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIB7Rbkn2hlkwQFt1fYp-mZDlvE20UPrQ',
    appId: '1:54170088721:android:aa859a21e16109de6a48b0',
    messagingSenderId: '54170088721',
    projectId: 'ayursage-146ed',
    storageBucket: 'ayursage-146ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqOBuQuRjSj1MHwFpw1zjnbzo30JAJvdA',
    appId: '1:54170088721:ios:bbb00d9b6e3e663d6a48b0',
    messagingSenderId: '54170088721',
    projectId: 'ayursage-146ed',
    storageBucket: 'ayursage-146ed.appspot.com',
    iosBundleId: 'com.imeperial.ayursage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqOBuQuRjSj1MHwFpw1zjnbzo30JAJvdA',
    appId: '1:54170088721:ios:1069bb76eaabacd76a48b0',
    messagingSenderId: '54170088721',
    projectId: 'ayursage-146ed',
    storageBucket: 'ayursage-146ed.appspot.com',
    iosBundleId: 'com.imeperial.ayursage.RunnerTests',
  );
}
